import{i as a,S as u}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&r(o)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const m=document.querySelector(".form"),l=document.querySelector(".gallery"),p=document.querySelector("div"),d=document.querySelector("input"),f=()=>{const n=document.createElement("span");n.classList.add("loader"),p.append(n)},c=()=>{const n=document.querySelector(".loader");n&&n.remove()};m.addEventListener("submit",n=>{f(),l.innerHTML="",n.preventDefault();const s=d.value.trim();s!==""?h(s):(a.error({message:"Please enter a search term.",position:"center",transitionIn:"fadeInLeft"}),c())});function h(n){const i=`https://pixabay.com/api/?key=41764579-b97d65b31c0abd4efd9d4830e&q=${n}&image_type=photo&orientation=horizontal&safesearch=true`;fetch(i).then(r=>{if(r.ok)return r.json();throw new Error(r.status)}).then(r=>{if(r.hits.length===0)a.error({message:"Sorry, there are no images matching <br>your search query. Please try again!</br>",position:"center",transitionIn:"fadeInLeft"}),c();else{const e=r.hits.map(o=>`
            <li class="gallery-item"><a href="${o.largeImageURL}">
          <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}"></a>
          <p><b>Likes: </b>${o.likes}</p>
          <p><b>Views: </b>${o.views}</p>
          <p><b>Comments: </b>${o.comments}</p>
          <p><b>Downloads: </b>${o.downloads}</p>
          </li>`).join("");l.insertAdjacentHTML("beforeend",e),new u(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250}).on("show.simplelightbox").refresh(),c()}}).catch(r=>console.log(r))}
//# sourceMappingURL=commonHelpers.js.map
